name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

    paths:
          - '.github/workflows/pull_request'
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/auto_assign.yml'


