name: Asignar 

on:
  pull_request:
    types: [opened, ready_for_review]

  jobs:
    build:
      strategy:
        matrix:
          os: [linux-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        

  add-reviews:
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: 'Proyecto_Git/configuraciones.yml'
