name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: titenkov/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/some_name_for_configs.yml"