
name: Hotfix Action
on:
  pull_request:

jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to develop
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: hotfix
          base_branch: develop
          labels: hotfix,develop
          assignees: Adrian-AAB
          reviewers: Adrian-AAB
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to integration
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: hotfix
          base_branch: integration
          labels: hotfix,integration
          assignees: Adrian-AAB
          reviewers: Adrian-AAB