name: Pull Request Automation
on:
  pull_request_target:
    types: [labelled, unlabelled, opened, edited, reopened, synchronize, converted_to_draft, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]
  issue_comment:
    types: [created]

jobs:
  process:
    name: Process
    runs-on: ubuntu-latest
    steps:
    - uses: DrBarnabus/pullrequest-automation@v3 # latest matching major version 'v3' or specific version 'v2.4.1' or branch 'main'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        config-ref: master