name: Create Pull Request

on: [push]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Make changes to pull request here
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4