name: Demo_1

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.417
          5.0.406
          6.0.201
    - name: Install dependencies
      run: dotnet restore
    - name: Buil
      run: dotnet buil 
    - name: Test
      run: dotnet test


        