name: Demo 2 ~ CI and CD

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest #He cambiado el runner. Hay tres disponibles
        
        steps:
          - uses: actions/checkout@v2
          - name: Setup .NET Core
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: 3.1.101
          - name: Install dependencies
            run: dotnet restore
          - name: Buil
            run: dotnet buil --configuration Release --no-restore
          - name: Test
            run: dotnet test --no-restore --verbosity. normal
        #Añado el uso de artefactos 
          - name: Publish the code
            run: dotnet publish -c Release -0 ${{ env.DOTNET_ROOT }}/webapp
            workung-directory: ./Proyecto_Git
          - name: Upload artifact
            uses: actions/upload-artifact@v1
            with:
                name: webapp-artifact
                path: ${{ env.DOTNET_ROOT }}/webapp
            
    deploy:
        runs-on: windows-latest
        needs: [build] #Hay que esperar a que termine el job llamado build
        
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v1
            with:
                name: webapp-artifact
                path: ${{ env.DOTNET_ROOT }}/webapp
                
          - name: Deploy to Azure Web App
            uses: azure/webapps-deploy@v1
            witn: 
                slot-name: 'producction'
                package: ${{ env.DOTNET_ROOT }}/webapp
                publish-profile: ${{ secrets.WebAppPublishProfile }}
