 name: Enviar Mail 
  uses: bingblue/send-nodemailer@master
  with:
 
    user: '${{ secrets.MAIL_USER }}'
    pass: '${{ secrets.MAIL_PASS }}'
    host: 'smtp.exmail.qq.com'
    port: 465
    secure: true
    from: 'Your Name <adrian.arias@dbnetcorp.com>'
    to: ad.ariasbarrera@gmail.com,adr.arias@duocuc.cl
    subject: 'this is email subject'
    html: '<p>mensaje de asignación<p>'
