name: dotnet package

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref  != 'refs/heads/master'}}
    steps:
    - uses: betanzos/check-commit-exist@v1
      with:
        # SHA of the commit to check if it exists.
        # REQUIRED
        commit: ${{ github.sha }}

        # Inverts the action job finish status
        # (if `success` will be `failure` and if `failure` will be `success`).
        # Can be one of: 'true' or 'false'. Wrong values causes to use default.
        invert: 'false'
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: master
        title: "An automatically created PR!"

    
    
    
    