name: dotnet package

on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
  commit_check:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref  != 'refs/heads/master' }}
    steps:
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: ${{ github.token }}
          seconds: 120 # Two minutes in seconds
          branch: ${{ github.ref_name }}
      # condicional para saber si existe un pull request
      - name: Print something if new commits are found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'True' }}
        run: echo ${{ steps.check-new-commits.outputs.new-commits-number }} 
      - name: github.event.created  
        if: ${{ github.event.created != 'true'}}
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: master
          title: "An automatically created PR!"

      - uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              console.log(commit);
            }
          run: echo 'github.event.commits'

      - name: Print another thing if new commits couldn't be found
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "You don't have new commits 🛑!"

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Print
        run: echo '${{ github.event.created }}'

    
#  ${{ github.ref }} Variable que entrega la ruta de la rama actual

#  ${{ github.ref_name }} Variable que entrega el nombre de la rama actual 

#  ${{ steps.check-new-commits.outputs.has-new-commits }} Variable que muestra si exist un nuevo commit, retorna True o false, 
#  si es True se reconoce que existe un commit, si es false es por que no encuentra ningún commit 

#  ${{ steps.check-new-commits.outputs.new-commits-number }} Variable que contiene la cantidad de pull request
      
