name: dotnet package

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
  commit_check:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref  != 'refs/heads/master'}}
    steps:
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: ${{ github.token }}
          seconds: 60 # One day in seconds
          branch: ${{ github.ref_name }}
      - name: Print something if new commits are found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'True' }}
        run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) ✅!"  
      - name: steps.check-new-commits.outputs.new-commits-number != 0
        if: ${{ steps.check-new-commits.outputs.new-commits-number >= 0  }} 
        run: echo "${{ steps.check-new-commits.outputs.new-commits-number }}" 
      - uses: actions/checkout@1.0.0
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: master
          title: "An automatically created PR!"
      
      - name: Print another thing if new commits couldn't be found
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "You don't have new commits 🛑!"
    
      