name: dotnet package

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref  != 'refs/heads/master'}}
    steps:
    - uses: actions/checkout@1.0.0
    - name: Check for new commits today
      id: check-new-commits
      uses: adriangl/check-new-commits-action@v1
      with:
        token: 'your_github_token'
        seconds: 86400 # One day in seconds
        branch: 'master'
      if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: master
        title: "An automatically created PR!"

    
    
    
    