name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  create-pr-on-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: master
        title: "An automatically created PR!"
    - name: nombre .ref  
      run: echo "${{ github.ref }}"
  
  automation:
    needs: create-pr-on-push
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to creator
      uses: thomaseizinger/assign-pr-creator-action@v1.0.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}